### ISSUE TITLE
Fibonacci memoization

### ISSUE THREAD

**Issue by renefx** [gabidevjava/big-o-notation#1]
Não to abrindo uma issue de brincadeira que nem o último não hehehe
Quero dar uma dica
# Situação

Seu fibonacci tem complexidade exponencial né? É possível fazer ele ser melhor, se liga:
Toda vez que você chama ele, você faz uma chamada recursiva chamando 2 funções fib e elas vão cada uma chamar 2 fibs novas. A gente pode representar isso com uma arvore de resoluções:
`fibonacci(n) = fibonacci(n-1) + fibonacci(n-2)`

```
// valores aqui apresentados são o 'n' que está sendo calculado, fib(n), não o resultado
5
└── 4 
│   └── 3 
│   │   └── 2
│   │   │   └── 1
│   │   │   └── 0
│   │   └── 1
│   └── 2
│       └── 1
│       └── 0
│
└── 3
    └── 2
    │   └── 1
    │   └── 0
    └── 1 
```
Nessa iterações vemos que algumas coisas estão sendo calculadas repetidas vezes:

- fib(2) - 3x
- fib(3) - 2x

# Idéia

Para evitar esse cálculo repetido, é uma boa salvar os valores já calculados em um dicionário (a chave é o n fib que você busca e o valor é o resultado que já foi calculado por alguma recursão anterior). Aí você ficaria com uma sacola de respostas para consulta.
Então, se o n for > 1 tem duas opções:

1. Não tem o valor na sacola. Logo, você chama a recursão e ao receber o resultado, salva no dicionário.
2. Tem o valor, então você só retorna o resultado sem ter que chamar a recursão.

Esse mesmo exemplo de cima ficaria assim: 
(assumindo que o código vai executar o `fibonacci(n-1)` primeiro
ele vai tentar resolver como se fosse linha a linha de cima pra baixo) 
```
5 ✅
└── 4  ✅
│   └── 3 ✅ (não achou, chama a recursão)
│   │   └── 2 ✅ (não achou, chama a recursão)
│   │   │   └── 1 ❎ (já tem o resultado pq n <= 1)
│   │   │   └── 0 ❎ (já tem o resultado pq n <= 1 mas ao retornar para fib(2), salva no dicionário o resultado de fib(2))
│   │   │   Dicionário (n, resultado) { (2, 2) }
│   │   │
│   │   └── 1 ❎ (já tem o resultado, mas agora ao retornar, a recursão terá o resultado de fib(3) e salva no dicionário)
│   │       Dicionário (n, resultado) { (2, 2), (3, 3) }
│   │ 
│   └── 2 ❌ (achou no dicionário que o valor de 2 é 2)
│
└── 3 ❌ (achou no dicionário que o valor de 3 é 3)
```

O dicionário começa vazio e vai aumentando

# Análise de Complexidade

✅ - esses checkmarks indicam as vezes que o código teve que chamar uma recursão (4x)
❎ - esse checkmarks indicam que não foi preciso chamar uma recursão pq ele caiu naquele if n <= 0 (2x)
❌ - esse x indica que não foi necessário a recursão, mas teve que olhar no dicionário (2x)

## Tempo
Indo de baixo pra cima:
❌ - esse x que ocorreu 2x tem complexidade constante pq a consulta em um dicionário é O(1). Se toda a execução do código fosse desse x, o código seria de complexidade constante, mesmo que ocorram várias vezes é considerado O(1)
❎ - esse chackmark tbm é tempo constante O(1), pois é o mesmo caso de jogar uma moeda, só tem duas resoluções

Então até agora, se o código só tivesse esses dois tipos, ele seria constante.

✅ - esse checkmark indica que teve que chamar a recursão. Seria O(2^n), porém, por conta do dicionário, sempre que a gente chamar uma recursão, ao ir resolver o segundo elemento `fibonacci(n-2)` a gente já vai ter o resultado dele. Isso acontece pq ao pedir o fib(5) resolvemos o fib(4) primeiro - que é o fib(3) + fib(2). Ao finalizar de resolver o fib(4) já temos no dicionário o fib(3). e quando passamos a resolver a segunda parte do fib(5) que falta o fib(3), já pegamos no dicionário e o dicionário é O(1). 
`fibonacci(n) = fibonacci(n-1) + fibonacci(n-2)`

Isso faz com que só precisemos resolver uma única vez o fib de cada um dos números. Diferente do que ocorria que eram calculados:
- fib(2) - 3x
- fib(3) - 2x

Então se é ´so uma vez para cada um dos números até n, quer dizer que executamos o cálculo n vezes. 
**Complexidade de tempo linear O(n)**

## Espaço
Outra situação que ocorre é que agora temos um elemento na memória, o dicionário como sendo uma sacola de resultados. Antes não havia nada, então a complexidade de espaço era constante, nunca mudava independente do n a ser calculado.

Agora, se calculamos um n = 5 teremos um dicionário com 5 elementos, n = 1000, um dicionário com 1000. O dicionário cresce e ocupa mais espaço de memória se o n for maior. Mas claramente ele só pode guardar um elemento do n (não pode ter chave repetida) e por isso: 
**a complexidade de espaço é também linear O(n)**

# Resposta
Como professor não posso dar a resposta pro problema, mas o nome dessa solução (que pode ser aplicada em outros problemas recursivos) é **memoization**, eu não escrevi errado hahaha

**Comment by gabidevjava** [comment]
Suuuuper bacana!!! Rene. Gostei muito da sua issue. Gostei d+ da sua explicação. Agradeço.

Esse primeiro algoritmo de fibonacci, foi pra mostrar mesmo a sua complexidade:

_EXPONENCIAL: também é bem ruim, pois o número de instruções também cresce muito rapidamente (exponencialmente), ainda que numa taxa menos do que o anterior. É o caso de algoritmos que fazem busca em árvores binárias não ordenadas._

Quando mencionamos a **Memoization**, **Bottom-up**, **Shortest Paths** e **Guessing**, podemos ligar à Dynamic Programming (Programação dinâmica).

E na programação dinâmica temos que dividir pra conquistar.

> Um problema não pode depender de um resultado de outro problema que não pode ser resolvido.

> Estratégia, dividir em subproblemas e pegar o resultado desses subproblemas e resolver o resto.

_Quero falar mais sobre Dynamic Programming (Programação dinâmica), no repositório de estruturas de dados._

Tratando de Memoization no fibonacci, temos:

```
import time
#Recursiva, complexidade O(n) com memorização (programação dinâmica)
def fib(n, computed = {0: 0, 1: 1}):
    if n not in computed:
        computed[n] = fib(n - 1, computed) + fib(n - 2, computed)
    return computed[n]

def main():
    n = int(input())
    t0= time.process_time()
    print( fib(n) )
    t1 = time.process_time() - t0
    print("Time elapsed: ",abs(t1 - t0))

if __name__ == "__main__":
    main()
```

**Comment by renefx** [comment]
Tooooop isso mesmo! Não sabia que tinha um repo pra programação dinâmica! Boto fé vou dar uma olhada tbm pra acompanhar 😁😁😁
